version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=tasksrise
    volumes:
      - taskrise_postgres_data:/bitnami/postgresql

volumes:
  taskrise_postgres_data: